---
# coreの設置
- name: Create core
  become: true
  become_user: solr
  shell: |
    /opt/solr/bin/solr create -c {{ solr_core_name }}

- name: remove managed-schema
  become: true
  become_user: solr
  shell: |
    rm -f /var/solr/data/{{ solr_core_name }}/conf/managed-schema

- name: copy to solrconfig.xml
  become: yes
  become: solr
  template:
    src: "solrconfig.xml.j2"
    dest: "/var/solr/data/{{ solr_core_name }}/conf/solrconfig.xml"

- name: Copy schema.xml
  copy:
    src: schema-2.3_ja.xml
    dest: "/var/solr/data/{{ solr_core_name }}/conf/schema.xml"
    owner: solr
    group: solr
    mode: 0644
